import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';

// Import the screens we built
import 'admin_login_screen.dart';
import 'admin_dashboard_screen.dart';

void main() async {
  // 1. Ensure Flutter bindings are initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the options generated by FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the App
  runApp(const DecartAdminApp());
}

class DecartAdminApp extends StatelessWidget {
  const DecartAdminApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Decart Admin',
      debugShowCheckedModeBanner: false, // This removes the red "DEBUG" banner
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF0F4C5C)),
        useMaterial3: true,
        fontFamily: 'Times New Roman', // Matches your main app branding
      ),
      home: const AuthWrapper(),
    );
  }
}

// This widget checks if the Admin is already logged in.
// If yes -> Dashboard. If no -> Login Screen.
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // While checking auth state, show a loading spinner
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(
              child: CircularProgressIndicator(color: Color(0xFF0F4C5C)),
            ),
          );
        }

        // If a user is currently logged in, go straight to the Dashboard
        if (snapshot.hasData && snapshot.data != null) {
          return const AdminDashboardScreen();
        }

        // Otherwise, show the Login Screen
        return const AdminLoginScreen();
      },
    );
  }
}